config/routes.rb
PrepareProject::Application.routes.draw do  

  

  resources :amount_remains

  resources :roles

  resources :harams

  resources :send_links
  devise_for :users
  resources :users do 
    collection do 
      post "create_colleague" => "users#create"
    end
  end
  

scope "(:locale)", :locale => /en|fa|ar/ do  resources :resellers
 
  resources :sliders
  resources :activities
  resources :messages  
  resources :pictures
  get 'test' => 'static#test'
  resources :products do
    member do
      get :download
    end
  end
  resources :pages
  resources :categories
  resources :feeds, :only => [:index]

end
  root :to => 'static#home'
  
  get "login" => "users#login"  
  post "create_session" => "users#create_session", :as => :create_session
  get "delete_session" => "users#delete_session", :as => :delete_session
  

end

app/views/shared/_admin_menu.html.haml
.col-sm-6{:style => "border-left: 1px solid #FFA500"}  
  %p= link_to 'مدیریت بخش ها', Category, :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'افزودن آیتم به هر بخش', new_product_path  , :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'مدیریت اسلایدر اصلی', Slider, :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'مدیریت اسلایدر حرم مطهر', Haram  , :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'پیام های ارسالی', Message, :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'مدیریت فعالیت ها', Activity, :title => "هتل_مشهد_هتل_شادتوس"
.col-sm-6  
  %p= link_to 'مدیریت حساب ها', AmountRemain, :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'کاربران', User, :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'افزودن کاربر جدید', new_user_path  , :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'مدیریت صفحات متنی', Page  , :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'مشاهده ارسال لینکها', SendLink, :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to 'پروفایل مدیر', edit_user_path(current_user), :title => "هتل_مشهد_هتل_شادتوس"
  %p= link_to "خروج", destroy_user_session_path, :method => :delete, :title => "هتل_مشهد_هتل_شادتوس"

app/views/shared/_colleague_menu.html.haml
.col-sm-12
  %p= link_to 'مشاهده حساب ها', AmountRemain
  %p= link_to 'مشاهده پروفایل', current_user
  %p= link_to 'ویرایش پروفایل کاربر', edit_user_path(current_user)
  %p= link_to "خروج", destroy_user_session_path, :method => :delete
  

app/views/shared/_footer.html.haml
.footer-menu.set-center{:class => I18n.locale}
  %ul.total           

    %li
      %ul
        %li.head
          %b= t('session')
        - Category.all.each do |category|
          %li= link_to category.title, category , :title => "هتل_مشهد_هتل_شادتوس"       
        
    %li
      %ul
        %li.head
          %b= t('reserve')
        %li
        %li
    %li
      %ul
        %li.head
          %b= t('contact')
        %li= link_to t('send-msg'), Page.first , :title => "هتل_مشهد_هتل_شادتوس"       
        %li        
          = link_to  t('send-mail'), '#', "data-toggle" => "modal", "data-target" => ".bs-example-modal-sm", :title => "هتل_مشهد_هتل_شادتوس"
            


.modal.fade.bs-example-modal-sm{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title 
          = t ('send-mail')          
      .modal-body
        = render 'send_links/form'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

app/views/shared/_menu.html.haml
%ul.set-center
  = link_to root_path, :title => "هتل_مشهد_هتل_شادتوس" do
    %li#home.first{:class => ('active' if current_page?(root_path)) }
      = t('home')
  = link_to '#', :title => " هتل شادتوس_مرکز_خرید" do
    %li.gallery#category{:class => ('active' if current_page?(categories_path)) }
      =t('shopping') 
  = link_to '#', :title => " هتل شادتوس_هتل" do
    %li#hotel
      = t('hotel')
  = link_to '#', :title => " هتل شادتوس_نقاط_دیدنی_مشهد" do
    %li#sights
      = t('sights')
  = link_to Activity, :title => " هتل شادتوس_مرکز_فعالیتها" do
    %li{:class => ('active' if current_page?(activities_path)) }= t('activity')
  = link_to '#', :title => " هتل شادتوس_ارتباط_با_شادتوس" do
    %li#contact{:class => ('active' if current_page?(pages_path)) }
      = t('contact')
.col-sm-6.submenu.contact
  .close.pull-right 
    X
  - Page.all.each do |page|
    .col-sm-4.submenu-item      
      =link_to page, :title => " هتل شادتوس_"+ page.title do
        %b=page.title
        .submenu-image= image_tag page.image(:small), :title => "هتل_مشهد_هتل_شادتوس", :alt => "هتل_مشهد_هتل_شادتوس"
  .clr-float
.col-sm-6.submenu.category
  .close.pull-right 
    X
  - category = Category.where(category_type: 1)
  - category.each do |category|
    .col-sm-4.submenu-item      
      =link_to category, :title => " هتل شادتوس_"+ category.title do
        %b=category.title
        .submenu-image= image_tag category.image(:small), :title => "هتل_مشهد_هتل_شادتوس", :alt => "هتل_مشهد_هتل_شادتوس"
  .clr-float
  
.col-sm-6.submenu.hotel
  .close.pull-right 
    X
  - category = Category.find_by_category_type(2)
  - if category.present? && category.products.present?
    - category.products.each do |room|
      .col-sm-4.submenu-item      
        =link_to room, :title => " هتل شادتوس_"+ room.title  do
          %b=room.title
          - if room.pictures.present?
            .submenu-image= image_tag room.pictures.first.image(:small), :title => "هتل_مشهد_هتل_شادتوس", :alt => "هتل_مشهد_هتل_شادتوس"
    .clr-float
.col-sm-6.submenu.sights
  .close.pull-right 
    X
  - category = Category.find_by_category_type(3)
  - if category.present? && category.products.present?
    - category.products.each do |place|
      .col-sm-4.submenu-item           
        =link_to place, :title => " هتل شادتوس_"+ place.title  do
          %b=place.title
          - if place.pictures.present?
            .submenu-image= image_tag place.pictures.first.image(:small), :title => "هتل_مشهد_هتل_شادتوس", :alt => "هتل_مشهد_هتل_شادتوس"
  .clr-float
    
:javascript 
  $('#contact').click(function(){
    $('.submenu').hide();
    $('.submenu.contact').slideToggle('slow');
  });
  $('#category').click(function(){
    $('.submenu').hide();
    $('.submenu.category').slideToggle('slow');
  });
  $('#hotel').click(function(){
    $('.submenu').hide();
    $('.submenu.hotel').slideToggle('slow');
  });
  $('#sights').click(function(){
    $('.submenu').hide();
    $('.submenu.sights').slideToggle('slow');
  });
  $('.close').click(function(){
    $('.submenu').slideUp(500);
  });

app/views/shared/_msg_form.html.haml
%h4= t('msg.contact-title')
= form_for @message ||= Message.new, :html => {:class => "contact"} do |f|
  - if @message.errors.any?
    #error_explanation
      %ul
        - @message.errors.each do |attr, msg|
          %li= msg 
      
  -if flash[:SendMsg]        
    .alert.alert-success= flash[:SendMsg]
      
  
  .form-group
    = f.label t('msg.contact-name'),  :class => "control-label"    
    %span.Necessary= t('msg.Required')
    = f.text_field :name, :class => "form-control needed"  
    
    
  .form-group
    = f.label t('msg.contact-email'),  :class => "control-label"
    %span.Necessary= t('msg.Required')
    = f.text_field :email, :class => "form-control needed"          
    
  .form-group
    = f.label t('msg.contact-phone'),  :class => "control-label"
    = f.text_field :phone, :class => "form-control"
    
  .form-group
    = f.label t('msg.contact-msg'),  :class => "control-label"
    %span.Necessary=  t('msg.Required')
    = f.text_area :text, :class => "form-control needed", :style => "resize:none", :rows => 5
    
         
  .form-group
    = f.submit t('msg.contact-btn'), :class=> "send-msg"

:javascript   
  $(':submit.send-msg').click(function(e) {
    $(':text.needed, textarea.needed').each(function() {
      if ($(this).val().length == 0) {
        $(this).css('border', '2px solid red');
        e.preventDefault();
      }
    });
  });

app/views/shared/_upload_image_form.html.haml
.col-sm-12{:style => "margin-bottom:5%; border-bottom:#FFA500 solid 2px;"}
  
  .form-group.upload-pic
    - if picture.object.image.present? 
      = image_tag  picture.object.image(:small), :class => "enable_file_select"
    = picture.file_field :image    
    
  .col-sm-12
    
    .form-group
      = picture.label "عنوان به فارسی", :class => "control-label"   
      = picture.text_field :title_fa, :class => "form-control"
    .form-group
      = picture.label "عنوان به عربی", :class => "control-label"   
      = picture.text_field :title_ar, :class => "form-control"
    .form-group
      = picture.label "عنوان به انگلیسی", :class => " control-label"   
      = picture.text_field :title, :class => "form-control"
  
    .form-group
      = picture.label "توضیحات عکس به فارسی", :class => "control-label"   
      = picture.text_area :description_fa, :rows => 2, :class => "form-control"
    .form-group
      = picture.label "توضیحات عکس به عربی", :class => "control-label"   
      = picture.text_area :description_ar, :rows => 2, :class => "form-control"
    .form-group
      = picture.label "توضیحات عکس به انگلیسی", :class => "control-label"   
      = picture.text_area :description, :rows => 2, :class => "form-control"
    
    = picture.link_to_remove image_tag ("Delete_Icon.png"), :class => "remove-task "
    %span= 'حذف تصویر'
.clr-float