config/routes.rb
PrepareProject::Application.routes.draw do  

  

  resources :amount_remains

  resources :roles

  resources :harams

  resources :send_links
  devise_for :users
  resources :users do 
    collection do 
      post "create_colleague" => "users#create"
    end
  end
  

scope "(:locale)", :locale => /en|fa|ar/ do  resources :resellers
 
  resources :sliders
  resources :activities
  resources :messages  
  resources :pictures
  get 'test' => 'static#test'
  resources :products do
    member do
      get :download
    end
  end
  resources :pages
  resources :categories
  resources :feeds, :only => [:index]

end
  root :to => 'static#home'
  
  get "login" => "users#login"  
  post "create_session" => "users#create_session", :as => :create_session
  get "delete_session" => "users#delete_session", :as => :delete_session
  

end

app/models/haram.rb
# encoding: UTF-8
class Haram < ActiveRecord::Base
  has_attached_file :image, :styles => { :original => "500x500#" , :medium => "300x300#", :small => "200x200#" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                            :message =>  "فرمت عکس صحیح نیست"
  def description
    if I18n.locale == :ar
      self.read_attribute("description_ar")
    elsif I18n.locale == :en
      self.read_attribute("description_en")
    else
      self.read_attribute("description_fa")
    end
    
  end
end

app/controllers/harams_controller.rb
class HaramsController < ApplicationController
  before_action :set_haram, only: [:show, :edit, :update, :destroy]
  before_filter :check_autentication
  # GET /harams
  # GET /harams.json
  def index
    @harams = Haram.all
  end

  # GET /harams/1
  # GET /harams/1.json
  def show
  end

  # GET /harams/new
  def new
    @haram = Haram.new
  end

  # GET /harams/1/edit
  def edit
  end

  # POST /harams
  # POST /harams.json
  def create
    @haram = Haram.new(haram_params)

    respond_to do |format|
      if @haram.save
        format.html { redirect_to @haram, notice: 'Haram was successfully created.' }
        format.json { render action: 'show', status: :created, location: @haram }
      else
        format.html { render action: 'new' }
        format.json { render json: @haram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /harams/1
  # PATCH/PUT /harams/1.json
  def update
    respond_to do |format|
      if @haram.update(haram_params)
        format.html { redirect_to @haram, notice: 'Haram was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @haram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /harams/1
  # DELETE /harams/1.json
  def destroy
    @haram.destroy
    respond_to do |format|
      format.html { redirect_to harams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_haram
      @haram = Haram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def haram_params
      params.require(:haram).permit(:description_fa, :description_en, :description_ar, :image)
    end
end

app/helpers/harams_helper.rb
module HaramsHelper
end

app/views/harams/_form.html.haml
= form_for @haram do |f|
  - if @haram.errors.any?
    #error_explanation      
      %ul
        - @haram.errors.each do |attr, msg|
          %li= msg
  .col-sm-9.set-center
    .form-group
      = f.label 'تصویر حرم', :class => "col-sm-5 control-label"      
      = f.file_field :image
    .form-group
      = f.label 'توضیحات به فارسی:', :class => "col-sm-5 control-label"      
      = f.text_field :description_fa, :class => "form-control"
    .form-group
      = f.label 'توضیحات به انگلیسی:', :class => "col-sm-5 control-label"      
      = f.text_field :description_en, :class => "form-control"
    .form-group
      = f.label 'توضیحات به عربی', :class => "col-sm-5 control-label"      
      = f.text_field :description_ar, :class => "form-control"
    
    .form-group
      = f.submit 'ثبت', :class=> "btn btn-default"

app/views/harams/_slider_haram.html.haml
#haram-slide-show.slide{:style => "height:100%"}
  .carousel-inner{:style => "height:100%"}
    - @sliders_haram = Haram.all
    - @sliders_haram.each do |slide|
      .item-row.item          
        = image_tag slide.image(:original), :id =>  slide.id ,  :class => "slide"          
        .haram-description{:class => I18n.locale}= 'توضیحات مربوط به هر اسلایدر در این  '
        -if is_admin?
          .row-controls.admin-edit-del
            = link_to edit_slider_path(slide) do
              %i= 'ویرایش'
              \|
            = link_to  slide, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }  do
              %i= 'حذف'
  -if @sliders_haram.count > 1                
    = link_to "#haram-slide-show", :class => "carousel-control left", "data-slide" => "prev" do
      = image_tag 'banner_go_left.png', :class => "haram-arrow"
    = link_to "#haram-slide-show", :class => "carousel-control right", "data-slide" => "next" do
      = image_tag 'banner_go_right.png', :class => "haram-arrow"
      
:javascript   
 
  $("#haram-slide-show .item").first().addClass("active");  
  $('#haram-slide-show').carousel();

app/views/harams/edit.html.haml
%h1 ویرایش اسلایدر حرم

= render 'form'
- if is_admin?
  = link_to 'مشاهده', @haram
  \|
  = link_to 'بازگشت', harams_path

app/views/harams/index.html.haml
.fa
  -if is_admin?
    = link_to new_haram_path, :class => "admin-access" do
      .admin-edit-del
        %i= 'تعریف آیتم جدید'
  %br
  %p
    %i= 'این تصاویر در قسمت اسلایدر حرم نمایش داده می شوند'
    %br
    سایز استاندارد برای این تصاویر ۲۸۰*۲۸۰ و حجم کمتر از ۵۰ کیلوبایت می باشد
    %br
  %h1= 'مدیریت اسلایدر حرم مطهر'

  .col-sm-12
    - @harams.each do |haram|
      .col-sm-3{:style => "margin:1%; height:300px"}
        = image_tag haram.image(:small)
        %p{:style => "margin:1%"}= haram.description        
        .admin-edit-del-small{:style => "width: 100%"}
          = link_to 'مشاهده', haram
          \|
          = link_to 'ویرایش', edit_haram_path(haram)
          \|
          = link_to 'حذف', haram, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }

  %br

  

app/views/harams/new.html.haml
%div
  %h1= 'آیتم جدید حرم مطهر'
  %p
    %i= 'تصویری از بارگاه ملکوتی را انتخاب کنید تا به اسلایدر تصاویر حرم مطهر افزوده شود'
  %hr
  .width80
    = render 'form'

  = link_to 'بازگشت', harams_path

app/views/harams/show.html.haml
.col-sm-12.fa
  = image_tag @haram.image(:small)
  %p
    %b توضیحات فارسی
    = @haram.description
  %p
    %b توضیحات انگلیسی
    = @haram.description_en
  %p
    %b توضیحات عربی
    = @haram.description_ar
  - if is_admin?
    .admin-edit-del-small
      = link_to 'ویرایش', edit_haram_path(@haram)
      \|
      = link_to 'بازگشت', harams_path