config/routes.rb
PrepareProject::Application.routes.draw do  

  

  resources :amount_remains

  resources :roles

  resources :harams

  resources :send_links
  devise_for :users
  resources :users do 
    collection do 
      post "create_colleague" => "users#create"
    end
  end
  

scope "(:locale)", :locale => /en|fa|ar/ do  resources :resellers
 
  resources :sliders
  resources :activities
  resources :messages  
  resources :pictures
  get 'test' => 'static#test'
  resources :products do
    member do
      get :download
    end
  end
  resources :pages
  resources :categories
  resources :feeds, :only => [:index]

end
  root :to => 'static#home'
  
  get "login" => "users#login"  
  post "create_session" => "users#create_session", :as => :create_session
  get "delete_session" => "users#delete_session", :as => :delete_session
  

end

app/models/picture.rb
# encoding: UTF-8
class Picture < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "500x500>" , :medium => "300x300>", :small => "200x200>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                            :message =>  "فرمت عکس صحیح نیست"
  belongs_to :product

  def title
    if I18n.locale == :ar
      self.read_attribute("title_ar")
    elsif I18n.locale == :en
      self.read_attribute("title")
    else
      self.read_attribute("title_fa")
    end
    
  end
  
  def description
    if I18n.locale == :ar
      self.read_attribute("description_ar")
    elsif I18n.locale == :en
      self.read_attribute("description")
    else
      self.read_attribute("description_fa")
    end
    
  end
end

app/controllers/pictures_controller.rb
# encoding: UTF-8
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_filter :check_autentication
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.order("title_fa")
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:description, :product_id, :image, :description_fa, :description_ar, :title, :title_fa, :title_ar)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.haml
= form_for @picture do |f|
  - if @picture.errors.any?
    #error_explanation
      %ul
        - @picture.errors.each do |attr, msg|
          %li= msg

  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :product_id
    = f.number_field :product_id
  .actions
    = f.submit 'Save'

app/views/pictures/edit.html.haml
%h1 Editing picture

= render 'form'

= link_to 'Show', @picture
\|
= link_to 'Back', pictures_path

app/views/pictures/index.html.haml
%h1 Listing pictures

%table
  %tr
    %th Description
    %th Product
    %th
    %th
    %th

  - @pictures.each do |picture|
    %tr
      %td= picture.description
      %td= picture.product_id
      %td= link_to 'Show', picture
      %td= link_to 'Edit', edit_picture_path(picture)
      %td= link_to 'Destroy', picture, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Picture', new_picture_path

app/views/pictures/new.html.haml
%h1 New picture

= render 'form'

= link_to 'Back', pictures_path

app/views/pictures/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @picture.description
%p
  %b Product:
  = @picture.product_id

= link_to 'Edit', edit_picture_path(@picture)
\|
= link_to 'Back', pictures_path