config/routes.rb
PrepareProject::Application.routes.draw do  

  

  resources :amount_remains

  resources :roles

  resources :harams

  resources :send_links
  devise_for :users
  resources :users do 
    collection do 
      post "create_colleague" => "users#create"
    end
  end
  

scope "(:locale)", :locale => /en|fa|ar/ do  resources :resellers
 
  resources :sliders
  resources :activities
  resources :messages  
  resources :pictures
  get 'test' => 'static#test'
  resources :products do
    member do
      get :download
    end
  end
  resources :pages
  resources :categories
  resources :feeds, :only => [:index]

end
  root :to => 'static#home'
  
  get "login" => "users#login"  
  post "create_session" => "users#create_session", :as => :create_session
  get "delete_session" => "users#delete_session", :as => :delete_session
  

end

app/models/category.rb
# encoding: UTF-8
class Category < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :title_en
  has_attached_file :image, :styles => { :original => "500x500>" , :medium => "300x300>", :small => "150x150#" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                            :message =>  "فرمت عکس صحیح نیست"
                                            
  has_attached_file :font_image, :styles => { :original => "300x300>", :small => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                            :message =>  "فرمت عکس صحیح نیست"
                                            
  has_attached_file :slider_box, :styles => { :original => "300x300>", :small => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                            :message =>  "فرمت عکس صحیح نیست"
                                            
  has_many :products
  
  has_many :sliders
  validates :title_fa, :title_en, :title_ar,  :presence => {:message => 'عنوان گروه را وارد کنید.'}
  validates :category_type, :presence => {:message => 'نوع بخش را انتخاب کنید.'}
  
  def title
    if I18n.locale == :ar
      self.read_attribute("title_ar")
    elsif I18n.locale == :en
      self.read_attribute("title_en")
    else
      self.read_attribute("title_fa")
    end    
  end
  
  def description
    if I18n.locale == :ar
      self.read_attribute("description_ar")
    elsif I18n.locale == :en
      self.read_attribute("description_en")
    else
      self.read_attribute("description_fa")
    end    
  end
  
  
end

app/controllers/categories_controller.rb
# encoding: UTF-8
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :load_slides]
  before_filter :check_autentication, only: [ :edit, :update, :destroy]
  before_filter :load_slides, only:[:show]
  # GET /categories
  # GET /categories.json
  def index
    
    @sliders = Slider.all
    
    @categories = Category.all  
    
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title_fa, :title_en, :description_fa, :description_en, :image, :title_ar, :description_ar, :slider_box, :category_type )
    end

    def load_slides
      @sliders = @category.sliders      
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= nested_form_for @category, :html => { :multipart => true  }  do |f|
  - if @category.errors.any?
    #error_explanation      
      %ul
        - @category.errors.each do |attr, msg|
          %li= msg
  
  .fa
    .col-sm-6      
      .form-group
        = f.label "عنوان بخش به فارسی", :class => "col-sm-5 control-label"    
        = f.text_field :title_fa, :class => "form-control"
      .form-group
        = f.label "عنوان بخش به انگلیسی", :class => "col-sm-5 control-label"      
        = f.text_field :title_en, :class => "form-control"    
      .form-group
        = f.label "عنوان بخش به عربی", :class => "col-sm-5 control-label"      
        = f.text_field :title_ar, :class => "form-control"  
      .form-group
        = f.label "بخش جاری در کدام دسته بندی قرار می گیرد؟", :class => "control-label"              
        %br
        =  f.select(:category_type, [['مرکز خرید',1], ['هتل',2],['سایر',3]] , prompt: "نوع بخش را انتخاب کنید.", :class => "form-control"  )
        
    .form-group.col-sm-6
      = f.label "توضیحات به فارسی", :class => "col-sm-5 control-label"      
      = f.text_area :description_fa, :class => "form-control"
    .form-group.col-sm-6
      = f.label "توضیحات به انگلیسی", :class => "col-sm-5 control-label"      
      = f.text_area :description_en, :class => "form-control"       
    .form-group.col-sm-6
      = f.label "توضیحات به عربی", :class => "col-sm-5 control-label"      
      = f.text_area :description_ar, :class => "form-control"       
    .clr-float
    
    .col-sm-6
      .form-group        
        = f.label " تصویر نمونه:", :class => "control-label"      
        = f.file_field :image     
        -if @category.image.present?              
          = image_tag @category.image(:small) 
    
      .form-group       
        = f.label " آیکنی که برای باکس این بخش روی اسلایدر اصلی قرار می گیرد.", :class => "control-label"      
        = f.file_field :slider_box     
        -if @category.font_image.present?              
          = image_tag @category.slider_box(:original) 
    
    
    .col-sm-6
      = f.submit 'ثبت', :class=> "btn btn-default"
  

app/views/categories/edit.html.haml
.fa
  %h1= 'ویرایش بخش' + " " + @category.title_fa
  %p
    %i= 'این صفحه برای ویرایش اطلاعات و توضیحات هر بخش که از قبل وارد نموده اید می باشد.'
  %hr  
  %div
    = render 'form'

 
  

app/views/categories/index.html.haml
.category-bg.fa
  -if is_admin?
    = link_to new_category_path, :class => "admin-access" do
      .admin-edit-del
        %i= 'تعریف بخش جدید'
    %i= 'حداکثر می توانید ۵ بخش اضافه کنید. برای افزودن بخش بیشتر لطفا هماهنگی لازم را انجام دهید.'
    %br
  .col-sm-9
    .AccordionBox
      %ul
        - @categories.each do |category|
          
          %li            
            -if is_admin? 
              .admin-edit-del-small
                = link_to 'ویرایش', edit_category_path(category)
                \|
                = link_to 'حذف', category, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }       
            = link_to category do
              = image_tag category.image(:original), :class => "sample-image"        
              .cat-title
                .col-sm-3= category.title
                %p.col-sm-8= category.description
        
:javascript

  $('.AccordionBox ul li:first').addClass('active');
  
  $('.AccordionBox ul li').mouseover(function(){
    $('.AccordionBox ul li').removeClass( "active" );
    $(this).addClass('active');
  });
      

app/views/categories/new.html.haml
.fa
  %h1= 'تعریف بخش جدید ' 
  %p
    %i= 'از این قسمت می توانید بخش جدید به سایت اضافه کنید. این بخشها در صفحه اصلی زیر اسلایدر بصورت کشویی نمایش داده خواهد شد.'
  %hr  
  %div
    = render 'form'

app/views/categories/show.html.haml
.main-bg
  -if is_admin? 
    .admin-edit-del.col-sm-3
      = link_to 'افزودن آیتم جدید', new_product_path(:category_id => @category.id)
    
    .col-sm-5  
      -#
        .col-sm-7.admin-edit-del
          = link_to 'افزودن زیرگروه', new_sub_group_path(:category_id => @category.id)
    .admin-edit-del-small.col-sm-2
      = link_to 'ویرایش', edit_category_path(@category)
      \|
      = link_to 'بازگشت', categories_path
    .clr-float
  
  
  .col-sm-12
    .col-sm-12.category-define
      .set-center          
        %h1.cat-title= @category.title      
        %p.cat-des= @category.description          
      
      -if I18n.locale == :en 
        = image_tag 'en-line.png', :class => "gold-line"
      - else 
        = image_tag 'line.png', :class => "gold-line"
    
    .col-sm-12.index-category      
                  
      - if  @category.products.present?
        - @category.products.each do |item|                
          .show-item.col-sm-3{:class => I18n.locale}                  
            
            = link_to product_path(item, :category_id => @category.id) do
              .sub_group_title
                %h3= item.title
                - if item.pictures.present?                  
                  = image_tag item.pictures.first.image(:small), :class => "resize-img"
                - else 
                  = image_tag 'missing.png', :class => "resize-img"

            .clr-float
            
              - if is_admin?
                .admin-edit-del-small
                  = link_to 'ویرایش', edit_product_path(item)
                  \|
                  = link_to 'حذف', item, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }